code of conduct and general updates
IATI/IATI-Developer-Documentation pull request #60
Opened 2021-09-16 08:01 UTC by nosvalds

[Trello](https://trello.com/c/B2QgrdaP)
- discuss to iaticonnect url change
- add developer code of conduct for GitHub
- update readme and gitignore with virutal env instructions

2021-09-16 13:24 UTC, PetyaKangalova approved these changes
The code of conduct text and general changes look good. There was a bit of code at the start that will leave for the dev review :)

2021-09-20 14:47 UTC, akmiller01 requested changes

2021-09-20 14:47 UTC, akmiller01 commented on code-of-conduct.rst
> +====================================
Just one issue found with the RST @nosvalds 

```
code-of-conduct.rst:2: WARNING: Title underline too short.

(GitHub) Contributor Covenant Code of Conduct
====================================
```

2021-09-20 15:26 UTC, akmiller01 approved these changes
:+1:

2021-09-20 15:28 UTC, merged